### ISSUE TITLE
evil-org-open-links stuck in infinite loop

### ISSUE THREAD

**Issue by ryanartecona** [edwtjo/evil-org-mode#14]
A couple times when I have triggered `evil-org-open-links` it has crashed Emacs. One failure mode I've noticed is it opens a single link in an infinite loop until eventually crashing, and the other is it logs messages in an infinite loop without opening any links.

I think the root cause is [on line 87](https://github.com/edwtjo/evil-org-mode/blob/master/evil-org.el#L87), if `org-next-link` can't find a link, or finds the same link under `(point)` over and over again.

**Comment by wsdookadr** [comment]
@ryanartecona Hey Ryan, just pushed a fix for this.
Can you try it out and confirm if this bug is fixed ?
