### ISSUE TITLE
Unable to use "Easy Template"?

### ISSUE THREAD

**Issue by x-ji** [edwtjo/evil-org-mode#16]
The shortcut for `easy template` in org mode should be <kbd><</kbd>. However it seems that what this key does in `evil-org-mode` is to jump words?

http://orgmode.org/manual/Easy-Templates.html

**Comment by wsdookadr** [comment]
@x-ji actually, it's true that [`<`](https://github.com/edwtjo/evil-org-mode/blob/master/evil-org.el#L110) and [`>`](https://github.com/edwtjo/evil-org-mode/blob/master/evil-org.el#L111) are bound to `org-metaleft` and `org-metaright` , but only in [`normal mode`](https://github.com/edwtjo/evil-org-mode/blob/master/evil-org.el#L93). in `insert mode` if you press if you write `<s` and then press `<TAB>` it will expand to the template.

**Comment by x-ji** [comment]
I see. Thanks.
