### ISSUE TITLE
Updating the README with new Evil clone url

### ISSUE THREAD

**Issue by wsdookadr** [edwtjo/evil-org-mode#19]
Gitorious.org will stay online until the end of May 2015 to give
    people time to migrate their repositories

[Gitorious is being acquired by GitLab](https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/) and the evil clone url will no longer be valid. I think the [evil clone url](https://github.com/edwtjo/evil-org-mode/blob/master/README.org#user-content-requirements) needs to be updated.

Not sure if evil has been transferred to GitLab yet. [gitlab.com/evil/evil](https://gitlab.com/evil/evil) shows a 404 (even when logged in)

Seems like [they haven't decided yet](http://thread.gmane.org/gmane.emacs.vim-emulation/2150/focus=2153) on where they will be hosting it next.

Evil is also [hosted here](https://bitbucket.org/lyro/evil/wiki/Home)

**Comment by edwtjo** [comment]
Thanks, for the report
