### ISSUE TITLE
("J" 'org-shiftdown) conflicts with (evil-join)

### ISSUE THREAD

**Issue by srustamo** [edwtjo/evil-org-mode#29]
It seems   `"J" 'org-shiftdown` was introduced recently, I did not have a conflict with `evil-join` before.

I tried to unset this with `  :config (define-key evil-org-mode-map "J" nil)` in `use-package` but no luck. Any idea how to unset this in an elegant way, without diving into the package's code?

**Comment by japhir** [comment]
Has an easy way of fixing this come up? I constantly find myself hitting this key combo and then feeling like an idiot when emacs tells me `To use shift-selection with Org-mode, customize `org-support-shift-select'`.

**Comment by japhir** [comment]
I configured my use-package evil-org like this to remove the J key from evil-org:

    (use-package evil-org
      :ensure t
      :bind
      (:map evil-org-mode-map
           ("J" . nil))
      :diminish evil-org-mode)

**Comment by srustamo** [comment]
Thanks, this seems to work.
