### ISSUE TITLE
Keybinds review and overhaul

### ISSUE THREAD

**Issue by edwtjo** [edwtjo/evil-org-mode#3]
Go through all functions in http://orgmode.org/manual/ and add/revise evil-org-mode-map

**Comment by jb55** [comment]
fyi spacemacs is removing H J K L bindings because they shadow common vim operations, perhaps it might be wise to review those?

**Comment by srustamo** [comment]
I can't comment on spacemacs, but <kbd>H J K L</kbd> should be at least user configurable. I end up with each pull commenting out <kbd>J</kbd> from the source.
