### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by shellhead** [edwtjo/evil-org-mode#35]
Hi @edwtjo, are you're still supporting this repository and accepting PRs?

**Comment by edwtjo** [comment]
I've dropped the use of org-mode in favor of a combination of gitit/taskwarrior so no I wouldn't say that I support this repo in any other way than that I'm still happy to accept PRs granted that there seems to be sufficient consensus, commits are in order and they don't introduce new weird behaviour.
